const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const sharp=require('C:/Users/User/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const root=path.resolve(__dirname,'../..'),stage=path.join(root,'artifacts/bounce-refresh-20260930/android'),store=path.join(stage,'play-store/current');
const walk=dir=>fs.readdirSync(dir,{withFileTypes:true}).flatMap(f=>f.isDirectory()?walk(path.join(dir,f.name)):[path.join(dir,f.name)]);
const put=(rel,data)=>{const p=path.join(stage,rel);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,data);};
(async()=>{
 const entries=[];
 for(const file of walk(path.join(store,'upload'))){
  const b=fs.readFileSync(file),m=await sharp(b).metadata(),rel=path.relative(store,file).replaceAll('\\','/');
  const expected=rel.includes('app-icon')?[512,512]:rel.includes('feature-graphic')?[1024,500]:[1920,1080];
  assert.deepEqual([m.width,m.height],expected,rel);assert.equal(m.hasAlpha,false,rel);assert.equal(m.format,'png');
  assert.ok(b.length<(rel.includes('app-icon')?1024:8192)*1024,rel);
  entries.push({file:rel,width:m.width,height:m.height,bytes:b.length,format:'RGB PNG',sha256:crypto.createHash('sha256').update(b).digest('hex'),source:rel.includes('/01-')||rel.includes('/02-')?'Existing Pixel gameplay capture; unchanged from 2026-09-29':rel.includes('/phone/')?'Current Android web payload in local Chromium at 2x pixel density; no UI retouching':'Promotional artwork, not a gameplay screenshot'});
 }
 assert.equal(entries.length,11);
 const counts={};
 for(const locale of ['en-US','he-IL']){counts[locale]={};for(const [field,limit]of [['app-name',30],['short-description',80],['full-description',4000]]){const s=fs.readFileSync(path.join(store,'copy',locale,field+'.txt'),'utf8').replaceAll('\r\n','\n').trim();counts[locale][field]=Array.from(s).length;assert.ok(counts[locale][field]<=limit,`${locale}/${field}`);}}
 put('play-store/current/asset-manifest.json',JSON.stringify({updated:'2026-09-30',app:'Minik Bounce & Learn',entries,listingCharacterCounts:counts},null,2)+'\n');
 const sections=['en-US','he-IL'].map(locale=>`<section id="${locale}"><h2>${locale==='en-US'?'English':'עברית'}</h2><a class="feature" href="upload/${locale}/feature-graphic-1024x500.png"><img src="upload/${locale}/feature-graphic-1024x500.png" alt="${locale==='en-US'?'Bounce & Learn feature graphic':'תמונת קידום מיניק מקפצים ולומדים'}"></a><p>Feature graphic · 1024 × 500 · RGB PNG</p><div class="grid">${entries.filter(e=>e.file.includes(locale+'/phone/')).map(e=>`<figure><a href="${e.file}"><img loading="lazy" src="${e.file}" alt="${path.basename(e.file)}"></a><figcaption>${path.basename(e.file)}<small>${e.source}</small></figcaption></figure>`).join('')}</div><p class="links">Listing copy: <a href="copy/${locale}/app-name.txt">Name</a><a href="copy/${locale}/short-description.txt">Short description</a><a href="copy/${locale}/full-description.txt">Full description</a></p></section>`).join('');
 put('play-store/current/preview.html',`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Minik Bounce & Learn — Current Play Store artwork</title><style>*{box-sizing:border-box}body{margin:0;background:#140c2a;color:#f6f1ff;font:16px/1.6 system-ui,sans-serif}main{max-width:1250px;margin:auto;padding:42px 24px}header{display:flex;align-items:center;gap:26px}header img{width:110px;height:110px;border-radius:24px}h1{font-size:clamp(25px,4vw,40px);line-height:1.15;margin:0}h2{font-size:28px}p,small{color:#c6beda}a{color:#8de7ff;text-underline-offset:4px}nav{display:flex;gap:24px;margin:26px 0}section{padding:24px 0 40px;border-top:1px solid #ffffff26}.feature img{width:100%;max-width:1024px;border-radius:20px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:22px}figure{margin:0;background:#ffffff08;padding:12px;border-radius:18px}.grid img{width:100%;border-radius:10px}figcaption{padding:10px 4px;overflow-wrap:anywhere}small{display:block;font-size:12px}.links a{display:inline-block;margin-inline:12px}footer{padding:24px;background:#25173d;border-radius:18px}@media(max-width:700px){.grid{grid-template-columns:1fr}header{align-items:flex-start}header img{width:70px;height:70px}}</style></head><body><main><header><a href="upload/common/app-icon-512.png"><img src="upload/common/app-icon-512.png" alt="Large ball above a golden arcade paddle"></a><div><h1>Minik Bounce &amp; Learn</h1><p>Current Play Store package · Updated 30 September 2026<br>Distinct Bounce branding. No Modern table-tennis artwork.</p></div></header><nav><a href="#en-US">English</a><a href="#he-IL">עברית</a><a href="upload/common/app-icon-512.png">512 × 512 Store icon</a><a href="asset-manifest.json">Verified file details</a></nav>${sections}<footer>This is the current upload set. Older dated and “superseded” folders are archives.<br>Gameplay/train images retain previous Pixel captures. Setup/help images are current app screens rendered locally, not new phone captures. The two feature graphics are promotional illustrations.<br>No Pixel device was used in this update. Nothing has been uploaded to Google Play.</footer></main></body></html>`);
 put('play-store/README.md','# Current Minik Bounce & Learn Store assets\n\nOpen [the visual gallery](current/preview.html). Use **current/upload/**, not the older dated or superseded folders.\n\n- [Store icon, 512 × 512](current/upload/common/app-icon-512.png)\n- [English feature, 1024 × 500](current/upload/en-US/feature-graphic-1024x500.png)\n- [Hebrew feature, 1024 × 500](current/upload/he-IL/feature-graphic-1024x500.png)\n- Four phone screenshots per language: current/upload/en-US/phone and current/upload/he-IL/phone.\n- English and Hebrew listing text: current/copy.\n\nSee [current/README.md](current/README.md) for capture provenance and formats.\n');
 put('play-store/current/README.md',`# Minik Bounce & Learn — current Store package\n\nUpdated 2026-09-30. Start with [preview.html](preview.html). Nothing has been published to Google Play.\n\n## Upload files\n\n- One shared 512 × 512 RGB PNG Store icon, under 1 MB: upload/common/app-icon-512.png.\n- One 1024 × 500 RGB PNG feature graphic per language: upload/en-US and upload/he-IL.\n- Four 1920 × 1080 RGB PNG phone screenshots per language, each under 8 MB, in numeric order: upload/<language>/phone.\n- Pasteable name, short description, and full description: copy/en-US and copy/he-IL.\n- [asset-manifest.json](asset-manifest.json) records dimensions, sizes, SHA-256 and capture provenance. All 11 upload graphics and six listing-text limits pass checks.\n\nThe icon is a large ball and golden arcade paddle on purple. The large train/balloon app illustration stays separate. Feature graphics and setup/help screenshot frames now use the new simple mark. No Modern table-tennis table, net, racket or player illustration is used.\n\n## Capture provenance\n\nPhone images 01 (Balloon Madness) and 02 (question train) are byte-for-byte copies of the previously approved 2026-09-29 Pixel captures and marketing frames. Images 03 (Help/progression) and 04 (setup) use the current Android web payload, rendered in local Chromium at a 960 × 432 viewport with 2x pixel density. The actual app capture is placed unchanged inside a marketing frame. No UI content was invented or retouched. These are not new physical-device captures. Feature graphics are promotional illustrations.\n\nSource HTML, local font and its license, original feature illustration and current raw setup/help captures are in source/. Pixel source captures remain in ../2026-09-29/source. Older dated/superseded folders are archives.\n\n## Regeneration\n\nThe paired iOS workspace contains tools/bounce-refresh/{prepare.cjs,qa.cjs,package.cjs,apply-android.py}. prepare creates reviewed staged files, qa captures actual app screens and renders marketing frames, package validates formats and produces this gallery, and apply copies staged files to Android. The Android branding/2026-09-30 folder preserves the generated original, 1024px master, launcher mask checks and prompt.\n\n## Device checks still pending\n\nPixel 3 and Pixel 6 launcher cropping (normal/themed icons), setup/help in English and Hebrew, Back from court to setup, system Back from setup, background/resume. Neither phone was used for this update.\n\n## Platform references\n\nFormats follow [Google Play preview-asset guidance](https://support.google.com/googleplay/android-developer/answer/9866151?hl=en). The separate foreground/background and themed silhouette follow [Android adaptive-icon guidance](https://developer.android.com/develop/ui/compose/system/icon_design_adaptive).\n`);
 console.log(JSON.stringify({graphics:entries.length,listingCharacterCounts:counts,gallery:path.join(store,'preview.html')}));
})();
