// Generated from Android core/Learning.kt (QuestionBank.english / QuestionBank.world) by
// Scripts/audit-splash.py --write-facts. Do not edit by hand: the banks must match Android exactly.
// Curated, local, unambiguous. The first option is the verified correct answer.

extension QuestionBank {
    static let english: [Fact] = [
        Fact(en: "Which word names an animal?", he: "איזו מילה היא שם של חיה?",
             choicesEn: ["cat", "cup", "sun", "red"],
             choicesHe: ["cat", "cup", "sun", "red"],
             level: 0, whyEn: "A cat is an animal.", whyHe: "cat הוא חתול.", source: "original vocabulary"),
        Fact(en: "Which animal barks?", he: "מה פירוש המילה כלב באנגלית?",
             choicesEn: ["dog", "day", "door", "duck"],
             choicesHe: ["dog", "day", "door", "duck"],
             level: 0, whyEn: "A dog barks.", whyHe: "dog פירושו כלב.", source: "original vocabulary"),
        Fact(en: "Which word is a color?", he: "איזו מילה היא צבע?",
             choicesEn: ["blue", "bird", "book", "ball"],
             choicesHe: ["blue", "bird", "book", "ball"],
             level: 0, whyEn: "Blue is a color.", whyHe: "blue הוא כחול.", source: "original vocabulary"),
        Fact(en: "Choose the opposite of hot.", he: "בחרו את ההפך של hot.",
             choicesEn: ["cold", "tall", "fast", "new"],
             choicesHe: ["cold", "tall", "fast", "new"],
             level: 1, whyEn: "Hot and cold are opposites.", whyHe: "hot הוא חם, cold הוא קר.", source: "original vocabulary"),
        Fact(en: "One child, two ...", he: "ילד אחד: child. שניים: ...",
             choicesEn: ["children", "childs", "childes", "child"],
             choicesHe: ["children", "childs", "childes", "child"],
             level: 2, whyEn: "The plural of child is children.", whyHe: "צורת הרבים של child היא children.", source: "original grammar"),
        Fact(en: "Choose: She ... a book.", he: "השלימו: She ... a book.",
             choicesEn: ["reads", "read", "reading", "reader"],
             choicesHe: ["reads", "read", "reading", "reader"],
             level: 2, whyEn: "She reads a book.", whyHe: "עם she בזמן הווה משתמשים כאן ב־reads.", source: "original grammar"),
        Fact(en: "Which word means the same as quick?", he: "איזו מילה דומה במשמעותה ל־quick?",
             choicesEn: ["fast", "late", "slow", "quiet"],
             choicesHe: ["fast", "late", "slow", "quiet"],
             level: 3, whyEn: "Quick and fast describe speed.", whyHe: "quick ו־fast מתארות מהירות.", source: "original vocabulary"),
        Fact(en: "Choose the past tense of go.", he: "בחרו את צורת העבר של go.",
             choicesEn: ["went", "goed", "gone", "going"],
             choicesHe: ["went", "goed", "gone", "going"],
             level: 3, whyEn: "The simple past of go is went.", whyHe: "צורת העבר הפשוט של go היא went.", source: "original grammar"),
        Fact(en: "Which word names a fruit?", he: "איזו מילה היא שם של פרי?",
             choicesEn: ["apple", "chair", "shoe", "cloud"],
             choicesHe: ["apple", "chair", "shoe", "cloud"],
             level: 0, whyEn: "An apple is a fruit.", whyHe: "apple הוא תפוח, פרי.", source: "original reviewed vocabulary and grammar"),
        Fact(en: "Which word names a body part?", he: "איזו מילה היא חלק בגוף?",
             choicesEn: ["hand", "house", "hat", "hill"],
             choicesHe: ["hand", "house", "hat", "hill"],
             level: 0, whyEn: "A hand is part of your body.", whyHe: "hand פירושו יד.", source: "original reviewed vocabulary and grammar"),
        Fact(en: "Which word names a number?", he: "איזו מילה היא מספר?",
             choicesEn: ["five", "fish", "flower", "floor"],
             choicesHe: ["five", "fish", "flower", "floor"],
             level: 0, whyEn: "Five is the number 5.", whyHe: "five הוא המספר 5.", source: "original reviewed vocabulary and grammar"),
        Fact(en: "Choose the opposite of up.", he: "בחרו את ההפך של up.",
             choicesEn: ["down", "over", "near", "with"],
             choicesHe: ["down", "over", "near", "with"],
             level: 1, whyEn: "Up and down are opposite directions.", whyHe: "up הוא למעלה, down הוא למטה.", source: "original reviewed vocabulary and grammar"),
        Fact(en: "Choose the opposite of empty.", he: "בחרו את ההפך של empty.",
             choicesEn: ["full", "small", "soft", "young"],
             choicesHe: ["full", "small", "soft", "young"],
             level: 1, whyEn: "Empty and full are opposites.", whyHe: "empty הוא ריק, full הוא מלא.", source: "original reviewed vocabulary and grammar"),
        Fact(en: "Which word names a place to read books?", he: "באיזה מקום אפשר לקרוא ולשאול ספרים?",
             choicesEn: ["library", "bakery", "garage", "kitchen"],
             choicesHe: ["library", "bakery", "garage", "kitchen"],
             level: 1, whyEn: "A library lends books to readers.", whyHe: "library היא ספרייה.", source: "original reviewed vocabulary and grammar"),
        Fact(en: "One mouse, two ...", he: "עכבר אחד: mouse. שניים: ...",
             choicesEn: ["mice", "mouses", "mouse", "micing"],
             choicesHe: ["mice", "mouses", "mouse", "micing"],
             level: 2, whyEn: "The plural of mouse is mice.", whyHe: "צורת הרבים של mouse היא mice.", source: "original reviewed vocabulary and grammar"),
        Fact(en: "Choose: They ... happy.", he: "השלימו: They ... happy.",
             choicesEn: ["are", "is", "am", "be"],
             choicesHe: ["are", "is", "am", "be"],
             level: 2, whyEn: "They are happy.", whyHe: "עם they משתמשים כאן ב-are.", source: "original reviewed vocabulary and grammar"),
        Fact(en: "Choose: Yesterday I ... a bird.", he: "השלימו: Yesterday I ... a bird.",
             choicesEn: ["saw", "see", "seen", "seeing"],
             choicesHe: ["saw", "see", "seen", "seeing"],
             level: 3, whyEn: "Saw is the simple past of see.", whyHe: "saw היא צורת העבר הפשוט של see.", source: "original reviewed vocabulary and grammar"),
        Fact(en: "Choose: This tree is ... than that one.", he: "השלימו: This tree is ... than that one.",
             choicesEn: ["taller", "tallest", "tall", "tallness"],
             choicesHe: ["taller", "tallest", "tall", "tallness"],
             level: 3, whyEn: "Taller compares the height of two things.", whyHe: "taller משווה גובה בין שני דברים.", source: "original reviewed vocabulary and grammar"),
        Fact(en: "Which word tells how someone runs?", he: "איזו מילה מתארת כיצד מישהו רץ?",
             choicesEn: ["quickly", "quick", "quicker", "quickest"],
             choicesHe: ["quickly", "quick", "quicker", "quickest"],
             level: 4, whyEn: "Quickly is an adverb describing how an action happens.", whyHe: "quickly מתארת איך הפעולה מתבצעת.", source: "original reviewed vocabulary and grammar"),
        Fact(en: "Choose: I have ... my homework.", he: "השלימו: I have ... my homework.",
             choicesEn: ["finished", "finish", "finishing", "finishes"],
             choicesHe: ["finished", "finish", "finishing", "finishes"],
             level: 4, whyEn: "Have finished uses the past participle.", whyHe: "אחרי have משתמשים כאן ב-finished.", source: "original reviewed vocabulary and grammar"),
        Fact(en: "Which word means to look at something carefully?", he: "איזו מילה פירושה להתבונן במשהו בקפידה?",
             choicesEn: ["observe", "ignore", "forget", "guess"],
             choicesHe: ["observe", "ignore", "forget", "guess"],
             level: 4, whyEn: "To observe is to look at or notice carefully.", whyHe: "observe פירושו להתבונן בקפידה.", source: "original reviewed vocabulary and grammar"),
        Fact(en: "Choose: If it rains, we ... stay inside.", he: "השלימו: If it rains, we ... stay inside.",
             choicesEn: ["will", "would", "were", "did"],
             choicesHe: ["will", "would", "were", "did"],
             level: 5, whyEn: "Will fits this possible future condition.", whyHe: "will מתאים לתוצאה עתידית אפשרית.", source: "original reviewed vocabulary and grammar"),
        Fact(en: "Choose: The book ... I borrowed is great.", he: "השלימו: The book ... I borrowed is great.",
             choicesEn: ["that", "who", "where", "when"],
             choicesHe: ["that", "who", "where", "when"],
             level: 5, whyEn: "That can refer to the book in this sentence.", whyHe: "that מתייחס כאן לספר.", source: "original reviewed vocabulary and grammar"),
        Fact(en: "Which word means unwilling to give up?", he: "איזו מילה מתארת מישהו שאינו מוותר בקלות?",
             choicesEn: ["persistent", "careless", "silent", "temporary"],
             choicesHe: ["persistent", "careless", "silent", "temporary"],
             level: 5, whyEn: "Persistent means continuing despite difficulty.", whyHe: "persistent מתאר התמדה למרות קושי.", source: "original reviewed vocabulary and grammar")
    ]

    static let world: [Fact] = [
        Fact(en: "What kind of object is the Sun?", he: "איזה גוף הוא השמש?",
             choicesEn: ["Star", "Planet", "Moon", "Comet"],
             choicesHe: ["כוכב", "כוכב לכת", "ירח", "שביט"],
             level: 0, whyEn: "The Sun is our nearest star.", whyHe: "השמש היא הכוכב הקרוב אלינו.", source: "https://science.nasa.gov/sun/facts/"),
        Fact(en: "How many natural moons does Earth have?", he: "כמה ירחים טבעיים יש לכדור הארץ?",
             choicesEn: ["1", "2", "3", "4"],
             choicesHe: ["1", "2", "3", "4"],
             level: 0, whyEn: "Earth has one natural moon.", whyHe: "לכדור הארץ ירח טבעי אחד.", source: "https://science.nasa.gov/earth/facts/"),
        Fact(en: "Which ocean is the largest?", he: "איזה אוקיינוס הוא הגדול ביותר?",
             choicesEn: ["Pacific", "Atlantic", "Indian", "Arctic"],
             choicesHe: ["השקט", "האטלנטי", "ההודי", "הארקטי"],
             level: 1, whyEn: "The Pacific is the largest ocean basin.", whyHe: "האוקיינוס השקט הוא הגדול ביותר.", source: "https://oceanservice.noaa.gov/facts/biggestocean.html"),
        Fact(en: "How many planets orbit our Sun?", he: "כמה כוכבי לכת מקיפים את השמש?",
             choicesEn: ["8", "6", "7", "9"],
             choicesHe: ["8", "6", "7", "9"],
             level: 1, whyEn: "Our solar system has eight planets.", whyHe: "במערכת השמש שמונה כוכבי לכת.", source: "https://science.nasa.gov/solar-system/solar-system-facts/"),
        Fact(en: "Which ocean is second largest?", he: "איזה אוקיינוס הוא השני בגודלו?",
             choicesEn: ["Atlantic", "Arctic", "Indian", "Southern"],
             choicesHe: ["האטלנטי", "הארקטי", "ההודי", "הדרומי"],
             level: 2, whyEn: "The Atlantic is second after the Pacific.", whyHe: "האטלנטי הוא השני בגודלו, אחרי השקט.", source: "https://oceanservice.noaa.gov/facts/biggestocean.html"),
        Fact(en: "What holds planets in orbit around the Sun?", he: "מה מחזיק את כוכבי הלכת במסלול סביב השמש?",
             choicesEn: ["Gravity", "Wind", "Sound", "Rain"],
             choicesHe: ["כבידה", "רוח", "קול", "גשם"],
             level: 3, whyEn: "Gravity keeps planets in orbit.", whyHe: "כוח הכבידה מחזיק כוכבי לכת במסלול.", source: "https://science.nasa.gov/solar-system/solar-system-facts/"),
        Fact(en: "Which is the largest planet in our solar system?", he: "מהו כוכב הלכת הגדול במערכת השמש?",
             choicesEn: ["Jupiter", "Mars", "Earth", "Venus"],
             choicesHe: ["צדק", "מאדים", "כדור הארץ", "נוגה"],
             level: 1, whyEn: "Jupiter is larger than the other planets.", whyHe: "צדק גדול משאר כוכבי הלכת.", source: "https://science.nasa.gov/jupiter/jupiter-facts/"),
        Fact(en: "Which is the hottest planet in our solar system?", he: "מהו כוכב הלכת החם במערכת השמש?",
             choicesEn: ["Venus", "Mercury", "Mars", "Neptune"],
             choicesHe: ["נוגה", "כוכב חמה", "מאדים", "נפטון"],
             level: 2, whyEn: "Venus has a thick heat-trapping atmosphere.", whyHe: "לנוגה אטמוספרה עבה הלוכדת חום.", source: "https://science.nasa.gov/venus/venus-facts/"),
        Fact(en: "Which galaxy contains our solar system?", he: "באיזו גלקסיה נמצאת מערכת השמש?",
             choicesEn: ["Milky Way", "Andromeda", "Whirlpool", "Sombrero"],
             choicesHe: ["שביל החלב", "אנדרומדה", "המערבולת", "סומבררו"],
             level: 3, whyEn: "Our solar system is part of the Milky Way.", whyHe: "מערכת השמש נמצאת בגלקסיית שביל החלב.", source: "https://science.nasa.gov/solar-system/"),
        Fact(en: "Which planet spins once in about ten hours?", he: "איזה כוכב לכת משלים סיבוב בכעשר שעות?",
             choicesEn: ["Jupiter", "Earth", "Venus", "Mars"],
             choicesHe: ["צדק", "כדור הארץ", "נוגה", "מאדים"],
             level: 4, whyEn: "Jupiter's rotation takes about 9.9 hours.", whyHe: "צדק משלים סיבוב סביב צירו בכ-9.9 שעות.", source: "https://science.nasa.gov/jupiter/jupiter-facts/"),
        Fact(en: "Which moon is the largest in our solar system?", he: "מהו הירח הגדול במערכת השמש?",
             choicesEn: ["Ganymede", "Europa", "Io", "Luna"],
             choicesHe: ["גנימד", "אירופה", "איו", "הירח שלנו"],
             level: 4, whyEn: "Ganymede is even larger than Mercury.", whyHe: "גנימד גדול אפילו מכוכב חמה.", source: "https://science.nasa.gov/jupiter/jupiter-facts/"),
        Fact(en: "Which gas makes up most of Venus's atmosphere?", he: "איזה גז מהווה את רוב האטמוספרה של נוגה?",
             choicesEn: ["CO₂", "Oxygen", "Hydrogen", "Helium"],
             choicesHe: ["פחמן דו-חמצני", "חמצן", "מימן", "הליום"],
             level: 5, whyEn: "The atmosphere of Venus is mostly carbon dioxide.", whyHe: "האטמוספרה של נוגה מורכבת בעיקר מפחמן דו-חמצני.", source: "https://science.nasa.gov/venus/venus-facts/")
    ]
}
