const fs=require('fs');
const {initializeTestEnvironment,assertSucceeds,assertFails}=require('@firebase/rules-unit-testing');
const {ref,set,get,update}=require('firebase/database');
(async()=>{
 const env=await initializeTestEnvironment({projectId:'demo-minik-amudu',database:{host:'127.0.0.1',port:Number(process.env.AMUDU_DATABASE_PORT||9006),rules:fs.readFileSync(__dirname+'/database.rules.json','utf8')}});
 const db=id=>env.authenticatedContext(id).database(),host=db('host'),alice=db('alice'),bob=db('bob'),outsider=db('outsider');
 const room='minikAmudu/rooms/TEST23';let passed=0;
 const yes=async p=>{await assertSucceeds(p);passed++},no=async p=>{await assertFails(p);passed++};
 const member=(id,slot)=>({id,slot,name:id,character:'miniko',bot:false,hebrew:false,ready:false,connected:true});
 const cfg={scene:'PARK',ball:'FOAM',freeze:'FREEZE',participants:10,turns:0,daylight:"NOON",throwMode:"STANDARD",wind:"NONE",huddleSeconds:24};
 await env.withSecurityRulesDisabled(async ctx=>{await set(ref(ctx.database(),room),null)});
 await yes(set(ref(host,room),{meta:{host:'host',phase:'lobby',leaseUntil:Date.now()+8000,epoch:1,seed:1,config:cfg},members:{host:member('host','0')},slots:{0:'host'}}));
 await yes(set(ref(host,room+'/meta/config/ball'),'TENNIS'));
 await no(set(ref(host,room+'/meta/config/ball'),'UNKNOWN'));
 await yes(set(ref(host,room+'/meta/config/ball'),'FOAM'));
 await no(get(ref(env.unauthenticatedContext().database(),room+'/meta')));
 await yes(get(ref(alice,room+'/members/alice')));
 await yes(set(ref(alice,room+'/slots/1'),'alice'));await yes(set(ref(alice,room+'/members/alice'),member('alice','1')));
 await yes(set(ref(bob,room+'/slots/9'),'bob'));await yes(set(ref(bob,room+'/members/bob'),member('bob','9')));
 await no(set(ref(outsider,room+'/slots/10'),'outsider'));await no(set(ref(outsider,room+'/slots/1'),'outsider'));
 await no(set(ref(alice,room+'/members/host/ready'),true));await yes(set(ref(alice,room+'/members/alice/ready'),true));
 await no(set(ref(alice,room+'/members/alice/bot'),true));await no(set(ref(alice,room+'/members/alice/slot'),'2'));
 await yes(get(ref(alice,room+'/members')));await no(get(ref(outsider,room+'/members')));
 // Host-side lobby edits still obey the same name/identity validation as joins.
 await no(set(ref(host,room+'/members/bob/name'),'12345'));
 await no(set(ref(host,room+'/members/bob/name'),'https://bad.example'));
 await no(set(ref(host,room+'/members/bob/character'),'unknown'));
 await yes(set(ref(host,room+'/members/bob/name'),'נועה'));
 await no(set(ref(host,room+'/meta/config/participants'),13));
 await no(set(ref(host,room+'/meta/config/participants'),11));
 await no(set(ref(host,room+'/meta/config/daylight'),'MIDNIGHT'));
 await no(set(ref(host,room+'/meta/config/throwMode'),'AUTO'));
 await no(set(ref(host,room+'/meta/config/wind'),'HURRICANE'));
 await yes(set(ref(host,room+'/meta/config/daylight'),'NIGHT'));
 await yes(set(ref(host,room+'/meta/config/wind'),'FAST'));
 await yes(set(ref(host,room+'/meta/config/turns'),50));
 await yes(set(ref(host,room+'/meta/config/turns'),0));
 await yes(set(ref(host,room+'/meta/phase'),'playing'));
 await no(set(ref(outsider,room+'/slots/2'),'outsider'));
 await yes(set(ref(host,room+'/public'),{time:1,phase:'AIR',actors:{host:{penalties:0}},ball:{height:3}}));
 await yes(get(ref(alice,room+'/public')));await no(get(ref(outsider,room+'/public')));
 await no(set(ref(alice,room+'/public/actors/host/penalties'),99));
 await yes(set(ref(host,room+'/checkpoint'),{consumed:['event1']}));
 await no(get(ref(alice,room+'/checkpoint')));
 await yes(set(ref(alice,room+'/commands/alice/event1'),{type:'catch',at:Date.now()}));
 await no(set(ref(alice,room+'/commands/alice/event1'),{type:'duck',at:Date.now()}));
 await no(set(ref(alice,room+'/commands/host/event2'),{type:'throw',power:.5,at:Date.now()}));
 await no(set(ref(alice,room+'/commands/alice/end'),{type:'end',at:Date.now()}));
 await yes(set(ref(host,room+'/commands/host/end'),{type:'end',at:Date.now()}));
 await no(set(ref(alice,room+'/commands/alice/cheat'),{type:'catch',penalties:30,at:Date.now()}));
 await no(set(ref(alice,room+'/commands/alice/warp'),{type:'move',vector:[50,0],at:Date.now()}));
 await yes(set(ref(alice,room+'/commands/alice/aim'),{type:'aim',vector:[.6,.8],at:Date.now()}));
 await no(set(ref(alice,room+'/commands/alice/toss'),{type:'toss',power:9,drift:0,at:Date.now()}));
 await no(set(ref(alice,room+'/commands/alice/chat'),{type:'say',index:8,at:Date.now()}));
 await yes(set(ref(host,room+'/commands/alice/event1'),null));
 // Host is the excluded player: their device must not read the huddle proposals/votes.
 await yes(update(ref(host,room+'/public'),{phase:'HUDDLE',huddleTarget:'host',huddleSerial:1}));
 const h=room+'/huddles/h1';
 await yes(set(ref(host,h+'/meta'),{target:'host',leader:'alice',deadline:Date.now()+24000,botOnly:false}));
 await no(get(ref(host,h+'/suggestions')));await no(get(ref(host,h+'/votes')));
 await yes(get(ref(alice,h+'/suggestions')));
 await no(set(ref(host,h+'/suggestions/host'),'happy'));
 await no(set(ref(alice,h+'/suggestions/alice'),'dancing frog'));
 await no(set(ref(alice,h+'/suggestions/alice'),'קפטן בננה'));
 for(const word of ['Mooncake','Rápido','نجمة','खुशी','Sterretje','צפרדע'])await yes(set(ref(alice,h+'/suggestions/alice'),word));
 for(const word of ['https://bad','<tag>','123','bad name','a\nb'])await no(set(ref(alice,h+'/suggestions/alice'),word));
 await yes(set(ref(alice,h+'/suggestions/alice'),'frog'));
 await yes(set(ref(bob,h+'/suggestions/bob'),'בננה'));
 await no(set(ref(alice,h+'/suggestions/alice'),'a mean unreviewed name'));
 await no(set(ref(alice,h+'/votes/bob'),'alice'));
 await no(set(ref(bob,h+'/votes/bob'),'missing'));
 await yes(set(ref(alice,h+'/votes/alice'),'alice'));
 await no(set(ref(alice,h+'/result'),{name:'frog',winner:'alice',at:Date.now()}));
 await yes(set(ref(bob,h+'/votes/bob'),'alice'));
 await yes(set(ref(alice,h+'/result'),{name:'frog',winner:'alice',at:Date.now()}));
 await yes(get(ref(host,h+'/result')));
 await no(set(ref(alice,h+'/result'),{name:'panda',winner:'bob',at:Date.now()}));
 // A disconnected huddle coordinator can be replaced without exposing the target's secret.
 await yes(update(ref(host,room+'/public'),{huddleSerial:2}));
 const h2=room+'/huddles/h2',deadline2=Date.now()+24000;
 await yes(set(ref(host,h2+'/meta'),{target:'host',leader:'alice',deadline:deadline2,botOnly:false}));
 await no(update(ref(host,h2+'/meta'),{leader:'bob'})); // Alice is still connected.
 await yes(set(ref(alice,room+'/members/alice/connected'),false));
 await yes(update(ref(host,h2+'/meta'),{leader:'bob'}));
 await no(update(ref(host,h2+'/meta'),{target:'alice',deadline:deadline2+1000}));
 await no(get(ref(host,h2+'/suggestions')));
 await yes(set(ref(bob,h2+'/suggestions/bob'),'בננה'));
 await yes(set(ref(alice,h2+'/votes/alice'),'bob'));
 await yes(set(ref(bob,h2+'/votes/bob'),'bob'));
 await no(set(ref(alice,h2+'/result'),{name:'בננה',winner:'bob',at:Date.now()}));
 await yes(set(ref(bob,h2+'/result'),{name:'בננה',winner:'bob',at:Date.now()}));
 await yes(set(ref(alice,room+'/members/alice/connected'),true));
 const result={id:'TEST23',penalties:{host:3,alice:0,bob:1},winners:['alice'],elapsed:120};
 await no(set(ref(alice,room+'/results/final'),result));await yes(set(ref(host,room+'/results/final'),result));
 await no(set(ref(host,room+'/results/final'),{...result,elapsed:121}));await no(set(ref(host,room+'/results/final'),null));
 await no(set(ref(alice,room+'/meta/host'),'alice'));await yes(set(ref(host,room+'/meta/leaseUntil'),0));
 const meta=(await get(ref(alice,room+'/meta'))).val();
 await no(set(ref(alice,room+'/meta'),{...meta,host:'alice',epoch:2,leaseUntil:Date.now()+8000,config:{...meta.config,wind:'NONE'}}));
 await yes(set(ref(alice,room+'/meta'),{...meta,host:'alice',epoch:2,leaseUntil:Date.now()+8000}));
 await yes(get(ref(alice,room+'/checkpoint')));await no(set(ref(host,room+'/public/time'),500));
 await no(set(ref(alice,'minikPingPong/test'),true));await no(set(ref(alice,'minikSplash/test'),true));await no(set(ref(alice,'TripleShot/test'),true));
 console.log(JSON.stringify({passed,failed:0,namespace:room,productionWrites:0},null,2));await env.cleanup();
})().catch(e=>{console.error(e);process.exit(1)});
