const fs=require('fs');
const {initializeTestEnvironment,assertSucceeds,assertFails}=require('@firebase/rules-unit-testing');
const {ref,set,get,update}=require('firebase/database');
(async()=>{
 const env=await initializeTestEnvironment({projectId:'demo-minik-splash',database:{host:'127.0.0.1',port:Number(process.env.SPLASH_DATABASE_PORT||9005),rules:fs.readFileSync(__dirname+'/database.rules.json','utf8')}});
 const db=id=>env.authenticatedContext(id).database();const h=db('host'),a=db('alice'),b=db('bob'),stranger=db('stranger');
 const room='minikSplash/rooms/TEST23';
 const m=(id,slot)=>({id,slot,character:'miniko',team:0,bot:false,name:id,ready:false,connected:true});
 let count=0;
 async function yes(p){await assertSucceeds(p);count++}
 async function no(p){await assertFails(p);count++}
 await env.withSecurityRulesDisabled(async ctx=>{await set(ref(ctx.database(),room),null)});
 await yes(set(ref(h,room),{meta:{host:'host',phase:'lobby',mode:'TEAMS',topic:'MATH',seed:1,createdAt:Date.now(),leaseUntil:Date.now()+8000,epoch:1,round:1},members:{host:m('host','0')},slots:{'0':'host'}}));
 await no(get(ref(env.unauthenticatedContext().database(),room+'/meta')));
 await yes(set(ref(a,room+'/slots/1'),'alice'));
 await yes(set(ref(a,room+'/members/alice'),m('alice','1')));
 await no(set(ref(b,room+'/slots/1'),'bob'));
 await no(set(ref(b,room+'/slots/6'),'bob'));
 await no(set(ref(b,room+'/members/bob'),m('bob','1')));
 await yes(set(ref(a,room+'/members/alice/ready'),true));
 await no(set(ref(a,room+'/members/host/ready'),true));
 await no(set(ref(a,room+'/members/alice/bot'),true));
 await no(set(ref(h,room+'/meta/maxPlayers'),7));
 await yes(update(ref(h,room+'/meta'),{mode:'SOLO',maxPlayers:2}));
 await no(set(ref(b,room+'/slots/2'),'bob'));
 const extra={},slots={'0':'host','1':'alice'};
 for(let i=0;i<4;i++){const id='house'+i,slot=''+(i+2);extra[id]={...m(id,slot),bot:true,ready:true,character:['amber','comet','june','coach67'][i]};slots[slot]=id;}
 await yes(update(ref(h,room),{'meta/maxPlayers':6,members:{host:m('host','0'),alice:{...m('alice','1'),ready:true},...extra},slots}));
 await no(set(ref(b,room+'/slots/5'),'bob'));
 await yes(set(ref(a,room+'/profiles/alice'),{ADD:{level:1}}));
 await no(set(ref(a,room+'/profiles/host'),{ADD:{level:5}}));
 await yes(get(ref(h,room+'/profiles')));
 await no(get(ref(a,room+'/profiles')));
 const settings={walk:'EASY',throwing:'STANDARD',arena:'ANDROMEDA',court:false,balloons:'ALL_OVER',subjects:['MATH','ENGLISH']};
 await yes(set(ref(a,room+'/members/alice/settings'),settings));
 await no(set(ref(a,room+'/members/host/settings'),settings));
 await no(set(ref(a,room+'/members/alice/settings/walk'),'TELEPORT'));
 await no(set(ref(a,room+'/members/alice/settings/throwing'),'AUTO_SCORE'));
 await no(set(ref(a,room+'/members/alice/settings/subjects'),['MATH','INVALID']));
 await no(set(ref(a,room+'/members/alice/settings/court'),'false'));
 await yes(set(ref(h,room+'/meta/phase'),'playing'));
 await yes(set(ref(h,room+'/public'),{time:1,actors:{host:{score:0}},teamScores:[0,0]}));
 await yes(get(ref(a,room+'/public')));
 await no(get(ref(stranger,room+'/public')));
 await no(set(ref(a,room+'/public/actors/host/score'),99));
 await yes(set(ref(h,room+'/private/alice'),{question:{answer:'4',options:['1','2','3','4']}}));
 await yes(set(ref(h,room+'/private/host'),{question:{answer:'6'}}));
 await yes(get(ref(a,room+'/private/alice')));
 await no(get(ref(a,room+'/private/host')));
 await no(get(ref(a,room)));
 await no(get(ref(a,room+'/private')));
 await yes(set(ref(h,room+'/checkpoint'),{private:{host:{answer:'6'}},round:1}));
 await no(get(ref(a,room+'/checkpoint')));
 await yes(set(ref(a,room+'/commands/alice/one'),{type:'throw',at:Date.now()}));
 await no(set(ref(a,room+'/commands/alice/one'),{type:'jump',at:Date.now()}));
 await no(set(ref(a,room+'/commands/host/two'),{type:'throw',at:Date.now()}));
 await no(set(ref(a,room+'/commands/alice/cheat'),{type:'throw',at:Date.now(),score:500}));
 await no(set(ref(a,room+'/commands/alice/teleport'),{type:'move',x:500,y:0,at:Date.now()}));
 await no(set(ref(a,room+'/commands/alice/badindex'),{type:'pickup',qid:'q1',index:4,at:Date.now()}));
 await yes(set(ref(a,room+'/commands/alice/walk'),{type:'walkTo',x:2,y:3,qid:'q1',index:2,at:Date.now()}));
 await no(set(ref(a,room+'/commands/alice/walkFar'),{type:'walkTo',x:400,y:3,qid:'q1',index:2,at:Date.now()}));
 await no(set(ref(a,room+'/commands/alice/walkBad'),{type:'walkTo',x:2,y:3,qid:'q1',index:4,at:Date.now()}));
 await yes(set(ref(a,room+'/commands/alice/target'),{type:'shootAt',target:'host',at:Date.now()}));
 await no(set(ref(a,room+'/commands/alice/targetBad'),{type:'shootAt',target:'not-in-room',at:Date.now()}));
 await no(set(ref(a,room+'/commands/alice/targetScore'),{type:'shootAt',target:'host',score:99,at:Date.now()}));
 await yes(set(ref(h,room+'/commands/alice/one'),null));
 const result={id:'TEST23-r1',scores:{host:5,alice:3},teamScores:[5,3],draw:false,elapsed:180};
 await no(set(ref(a,room+'/results/r1'),result));
 await yes(set(ref(h,room+'/results/r1'),result));
 await no(set(ref(h,room+'/results/r1'),{...result,scores:{host:99}}));
 await no(set(ref(h,room+'/results/r1'),null));
 await no(set(ref(a,room+'/meta/host'),'alice'));
 await yes(set(ref(h,room+'/meta/leaseUntil'),0));
 const meta=(await get(ref(a,room+'/meta'))).val();
 await yes(set(ref(a,room+'/meta'),{...meta,host:'alice',epoch:2,leaseUntil:Date.now()+8000}));
 await yes(get(ref(a,room+'/checkpoint')));
 await no(set(ref(h,room+'/public/actors/host/score'),22));
 await no(set(ref(a,'minikPingPong/rooms/UNTOUCHED'),{anything:1}));
 await no(set(ref(a,'TripleShot/test'),{anything:1}));
 await yes(set(ref(a,room+'/meta/phase'),'finished'));
 await yes(update(ref(a,room),{'meta/round':2,'meta/phase':'lobby','members/host/ready':false,'members/alice/ready':false}));
 await no(get(ref(stranger,room+'/results')));
 console.log(JSON.stringify({passed:count,failed:0,namespace:room,productionWrites:0},null,2));
 await env.cleanup();
})().catch(e=>{console.error(e);process.exit(1)});
